In [15]:
import pandas as pd

# 加载数据集
file_path = '../Data/dream3/DREAM3_GeneExpressionChallenge_ExpressionData_UPDATED.txt'
df = pd.read_csv(file_path, sep='\t')







In [16]:
df

ProbeID geneName  \
0             10000_at      NaN   
1             10001_at     MID2   
2           10002_i_at      NaN   
3           10003_f_at   RPS25B   
4             10004_at      NaN   
...                ...      ...   
9330  AFFX-YER148w5_at    SPT15   
9331  AFFX-YER148wM_at    SPT15   
9332  AFFX-YFL039C3_at     ACT1   
9333  AFFX-YFL039C5_at     ACT1   
9334  AFFX-YFL039CM_at     ACT1   

      absolute expression, parental strain t=0 (arbitrary units)  wt t=0  \
0                                                 0.194                0   
1                                                 1.480                0   
2                                                13.960                0   
3                                               132.600                0   
4                                                 0.148                0   
...                                                 ...              ...   
9330                                              5.474                0   
9331                                             20.390                0   
9332                                             65.320                0   
9333                                             58.940                0   
9334                                             46.750                0   

       wt t=10   wt t=20   wt t=30   wt t=45   wt t=60   wt t=90  ...  \
0     0.080088 -0.021480 -0.207893  0.070967 -0.066261 -0.063503  ...   
1    -0.466758 -0.376290 -0.619178 -0.199123 -0.107018 -0.142740  ...   
2    -0.312665 -0.146655 -0.640621 -0.097611 -0.200379 -0.304511  ...   
3    -0.182692 -0.105678 -0.447844 -0.119024 -0.167358 -0.244887  ...   
4     0.164884  0.182786  0.186065  0.103147  0.129734  0.107803  ...   
...        ...       ...       ...       ...       ...       ...  ...   
9330  0.362158  0.375197  0.063409  0.224317  0.508403  0.494109  ...   
9331  0.242977  0.134477 -1.233275  0.202572  0.341903  0.531156  ...   
9332 -0.378512 -0.157044 -0.175045 -0.062122 -0.059355  0.023270  ...   
9333 -0.556797 -0.227741 -0.211635 -0.136191 -0.209141 -0.334568  ...   
9334 -0.397255 -0.163499 -0.153157 -0.092207 -0.160920 -0.140124  ...   

      gcn4-deletion t=90 gcn4-deletion t=120 leu3-deletion t=0  \
0               0.081614           -0.079975         -0.185232   
1               0.302226           -0.147958         -0.149259   
2              -0.478195           -0.610700         -0.385155   
3              -0.302173           -0.473008         -0.284514   
4               0.112475            0.349235          0.036526   
...                  ...                 ...               ...   
9330            0.533242            0.473931          0.072483   
9331            0.358454           -0.037031          0.054392   
9332            0.090803           -0.285698          0.275786   
9333           -0.250962           -0.695994         -0.157044   
9334           -0.117695           -0.449957          0.069452   

     leu3-deletion t=10 leu3-deletion t=20 leu3-deletion t=30  \
0             -0.205393          -0.071763          -0.060739   
1             -0.382944           0.182786          -0.007196   
2             -0.590722          -0.319618          -0.109695   
3             -0.492622          -0.358396          -0.404903   
4              0.013043          -0.005759           0.057392   
...                 ...                ...                ...   
9330           0.207561          -0.177599           0.112475   
9331           0.112475          -0.302173           0.063409   
9332           0.244685           0.586406           0.160040   
9333           0.134477           0.060397          -0.249749   
9334           0.226004           0.286304          -0.067639   

     leu3-deletion t=45 leu3-deletion t=60 leu3-deletion t=90  \
0              0.000000           0.042457          -0.146655   
1              0.020340          -0.052416           0.074001   
2             -0.468844          -0

In [17]:
# 清洗数据
# 1. 删除非必要的行（只保留有意义的表达数据）
df_cleaned = df.dropna(how='all', subset=df.columns[2:])  # 移除完全空的行

# 2. 转换数值列为浮点数（忽略可能的非数值条目如 "PREDICT"）
for col in df.columns[2:]:
    df_cleaned[col] = pd.to_numeric(df_cleaned[col], errors='coerce')

In [18]:
# 3. 重置索引
df_cleaned = df_cleaned.reset_index(drop=True)

# 4. 提取特征矩阵和目标变量（适合输入模型）
#    假设 "PREDICT" 的列是目标，需要预测，其他列作为特征。
feature_columns = [col for col in df_cleaned.columns if not col.startswith("gat1Δ") or "PREDICT" not in col]
target_columns = [col for col in df_cleaned.columns if "gat1Δ" in col]

# 创建特征和目标数据框
X = df_cleaned[feature_columns]  # 特征矩阵
y = df_cleaned[target_columns]  # 目标变量

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[9335 rows x 0 columns]

In [20]:
df_cleaned

ProbeID geneName  \
0             10000_at      NaN   
1             10001_at     MID2   
2           10002_i_at      NaN   
3           10003_f_at   RPS25B   
4             10004_at      NaN   
...                ...      ...   
9330  AFFX-YER148w5_at    SPT15   
9331  AFFX-YER148wM_at    SPT15   
9332  AFFX-YFL039C3_at     ACT1   
9333  AFFX-YFL039C5_at     ACT1   
9334  AFFX-YFL039CM_at     ACT1   

      absolute expression, parental strain t=0 (arbitrary units)  wt t=0  \
0                                                 0.194                0   
1                                                 1.480                0   
2                                                13.960                0   
3                                               132.600                0   
4                                                 0.148                0   
...                                                 ...              ...   
9330                                              5.474                0   
9331                                             20.390                0   
9332                                             65.320                0   
9333                                             58.940                0   
9334                                             46.750                0   

       wt t=10   wt t=20   wt t=30   wt t=45   wt t=60   wt t=90  ...  \
0     0.080088 -0.021480 -0.207893  0.070967 -0.066261 -0.063503  ...   
1    -0.466758 -0.376290 -0.619178 -0.199123 -0.107018 -0.142740  ...   
2    -0.312665 -0.146655 -0.640621 -0.097611 -0.200379 -0.304511  ...   
3    -0.182692 -0.105678 -0.447844 -0.119024 -0.167358 -0.244887  ...   
4     0.164884  0.182786  0.186065  0.103147  0.129734  0.107803  ...   
...        ...       ...       ...       ...       ...       ...  ...   
9330  0.362158  0.375197  0.063409  0.224317  0.508403  0.494109  ...   
9331  0.242977  0.134477 -1.233275  0.202572  0.341903  0.531156  ...   
9332 -0.378512 -0.157044 -0.175045 -0.062122 -0.059355  0.023270  ...   
9333 -0.556797 -0.227741 -0.211635 -0.136191 -0.209141 -0.334568  ...   
9334 -0.397255 -0.163499 -0.153157 -0.092207 -0.160920 -0.140124  ...   

      gcn4-deletion t=90  gcn4-deletion t=120  leu3-deletion t=0  \
0               0.081614            -0.079975          -0.185232   
1               0.302226            -0.147958          -0.149259   
2              -0.478195            -0.610700          -0.385155   
3              -0.302173            -0.473008          -0.284514   
4               0.112475             0.349235           0.036526   
...                  ...                  ...                ...   
9330            0.533242             0.473931           0.072483   
9331            0.358454            -0.037031           0.054392   
9332            0.090803            -0.285698           0.275786   
9333           -0.250962            -0.695994          -0.157044   
9334           -0.117695            -0.449957           0.069452   

      leu3-deletion t=10  leu3-deletion t=20  leu3-deletion t=30  \
0              -0.205393           -0.071763           -0.060739   
1              -0.382944            0.182786           -0.007196   
2              -0.590722           -0.319618           -0.109695   
3              -0.492622           -0.358396           -0.404903   
4               0.013043           -0.005759            0.057392   
...                  ...                 ...                 ...   
9330            0.207561           -0.177599            0.112475   
9331            0.112475           -0.302173            0.063409   
9332            0.244685            0.586406            0.160040   
9333            0.134477            0.060397           -0.249749   
9334            0.226004            0.286304           -0.067639   

      leu3-deletion t=45  leu3-deletion t=60  leu3-deletion t=90  \
0               0.000000            0.042457           -0.146655   
1               0.020340          

In [21]:
import pandas as pd

# 文件路径
expression_data_file = '../Data/dream3/DREAM3_GeneExpressionChallenge_ExpressionData_UPDATED.txt'
target_list_file = '../Data/dream3/DREAM3_GeneExpressionChallenge_TargetList.txt'

# 加载基因表达数据
expression_data = pd.read_csv(expression_data_file, sep='\t')

# 加载目标基因列表
target_list = pd.read_csv(target_list_file, sep='\t')

# 提取目标基因的 ProbeID 列表
target_probe_ids = target_list['ProbeID'].tolist()

# 清洗表达数据
# 1. 删除完全空的行
expression_data_cleaned = expression_data.dropna(how='all', subset=expression_data.columns[2:])

# 2. 转换数值列为浮点数，忽略 "PREDICT" 等非数值内容
for col in expression_data_cleaned.columns[2:]:
    expression_data_cleaned[col] = pd.to_numeric(expression_data_cleaned[col], errors='coerce')

# 3. 重置索引
expression_data_cleaned = expression_data_cleaned.reset_index(drop=True)

# 特征和目标数据提取
# 1. 提取目标基因数据
target_gene_data = expression_data_cleaned[expression_data_cleaned['ProbeID'].isin(target_probe_ids)]

# 2. 提取非目标基因数据
non_target_gene_data = expression_data_cleaned[~expression_data_cleaned['ProbeID'].isin(target_probe_ids)]

# 3. 特征矩阵：非目标基因的所有条件
X = non_target_gene_data

# 4. 目标变量：目标基因的 "gat1Δ" 条件，需处理 "PREDICT" 部分
y = target_gene_data.filter(like='gat1Δ')

# 检查结果
print("Feature Matrix (X):")
print(X.head())
print("\nTarget Data (y):")
print(y.head())


KeyError: 'ProbeID'

In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split

# 加载数据
expression_data_path = "../Data/dream3/DREAM3_GeneExpressionChallenge_ExpressionData_UPDATED.txt"
target_list_path = "../Data/dream3/DREAM3_GeneExpressionChallenge_TargetList.txt"

# 读取表达数据
expression_df = pd.read_csv(expression_data_path, sep="\t")
# 读取目标基因列表
target_list_df = pd.read_csv(target_list_path, sep="\t")

# 提取目标基因的 probeID
target_probe_ids = target_list_df["probeID"].dropna().tolist()

# 筛选非目标基因数据
non_target_data = expression_df[~expression_df["ProbeID"].isin(target_probe_ids)]

# 分离特征 (wt, gcn4, leu3) 和目标 (gat1)
# 特征列名包含 wt, gcn4, leu3，目标列名包含 gat1
feature_columns = [col for col in non_target_data.columns if any(cond in col for cond in ["wt", "gcn4", "leu3"])]
target_columns = [col for col in non_target_data.columns if "gat1" in col]

X = non_target_data[feature_columns].dropna()
Y = non_target_data[target_columns].dropna()

# 确保特征和目标对齐
X = X.loc[Y.index]
Y = Y.loc[X.index]

# 拆分为训练集和测试集 (70% 训练，30% 测试)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)


训练集大小: 6499
测试集大小: 2786


In [35]:
expression_df

ProbeID geneName  \
0             10000_at      NaN   
1             10001_at     MID2   
2           10002_i_at      NaN   
3           10003_f_at   RPS25B   
4             10004_at      NaN   
...                ...      ...   
9330  AFFX-YER148w5_at    SPT15   
9331  AFFX-YER148wM_at    SPT15   
9332  AFFX-YFL039C3_at     ACT1   
9333  AFFX-YFL039C5_at     ACT1   
9334  AFFX-YFL039CM_at     ACT1   

      absolute expression, parental strain t=0 (arbitrary units)  wt t=0  \
0                                                 0.194                0   
1                                                 1.480                0   
2                                                13.960                0   
3                                               132.600                0   
4                                                 0.148                0   
...                                                 ...              ...   
9330                                              5.474                0   
9331                                             20.390                0   
9332                                             65.320                0   
9333                                             58.940                0   
9334                                             46.750                0   

       wt t=10   wt t=20   wt t=30   wt t=45   wt t=60   wt t=90  ...  \
0     0.080088 -0.021480 -0.207893  0.070967 -0.066261 -0.063503  ...   
1    -0.466758 -0.376290 -0.619178 -0.199123 -0.107018 -0.142740  ...   
2    -0.312665 -0.146655 -0.640621 -0.097611 -0.200379 -0.304511  ...   
3    -0.182692 -0.105678 -0.447844 -0.119024 -0.167358 -0.244887  ...   
4     0.164884  0.182786  0.186065  0.103147  0.129734  0.107803  ...   
...        ...       ...       ...       ...       ...       ...  ...   
9330  0.362158  0.375197  0.063409  0.224317  0.508403  0.494109  ...   
9331  0.242977  0.134477 -1.233275  0.202572  0.341903  0.531156  ...   
9332 -0.378512 -0.157044 -0.175045 -0.062122 -0.059355  0.023270  ...   
9333 -0.556797 -0.227741 -0.211635 -0.136191 -0.209141 -0.334568  ...   
9334 -0.397255 -0.163499 -0.153157 -0.092207 -0.160920 -0.140124  ...   

      gcn4-deletion t=90 gcn4-deletion t=120 leu3-deletion t=0  \
0               0.081614           -0.079975         -0.185232   
1               0.302226           -0.147958         -0.149259   
2              -0.478195           -0.610700         -0.385155   
3              -0.302173           -0.473008         -0.284514   
4               0.112475            0.349235          0.036526   
...                  ...                 ...               ...   
9330            0.533242            0.473931          0.072483   
9331            0.358454           -0.037031          0.054392   
9332            0.090803           -0.285698          0.275786   
9333           -0.250962           -0.695994         -0.157044   
9334           -0.117695           -0.449957          0.069452   

     leu3-deletion t=10 leu3-deletion t=20 leu3-deletion t=30  \
0             -0.205393          -0.071763          -0.060739   
1             -0.382944           0.182786          -0.007196   
2             -0.590722          -0.319618          -0.109695   
3             -0.492622          -0.358396          -0.404903   
4              0.013043          -0.005759           0.057392   
...                 ...                ...                ...   
9330           0.207561          -0.177599           0.112475   
9331           0.112475          -0.302173           0.063409   
9332           0.244685           0.586406           0.160040   
9333           0.134477           0.060397          -0.249749   
9334           0.226004           0.286304          -0.067639   

     leu3-deletion t=45 leu3-deletion t=60 leu3-deletion t=90  \
0              0.000000           0.042457          -0.146655   
1              0.020340          -0.052416           0.074001   
2             -0.468844          -0

In [26]:
Y_train

gat1-deletion t=0 gat1-deletion t=10 gat1-deletion t=20  \
6783        0.15682011       -0.370722275       -0.041242982   
4511      -0.032806145       -0.458382004       -0.487486349   
203       -0.140124224        0.161653263        0.349235441   
6812      -0.185232254       -0.280956314       -0.199122642   
4878       0.293358943       -0.535057595       -0.320773477   
...                ...                ...                ...   
5770      -0.209141398       -0.319617934       -0.191562651   
5224       0.098505545        0.046921047       -0.115033243   
5425       0.293358943       -0.172487516        -0.10701825   
871       -0.097610797        0.131313235       -0.252173413   
7313      -0.250961574       -0.343692069       -0.884402553   

     gat1-deletion t=30 gat1-deletion t=45 gat1-deletion t=60  \
6783       -0.008630305        0.087733372       -0.005759269   
4511       -0.511973982       -0.591679417        -0.71633248   
203         0.639354798        0.734563104        0.311148256   
6812        0.100051014       -0.046840254        0.061902439   
4878       -0.074505436       -0.371837617        0.227692025   
...                 ...                ...                ...   
5770        0.106249498        0.204233052        0.134477041   
5224        0.103146927       -0.010063683        0.220950447   
5425        0.027674958       -0.236339539       -0.422233001   
871         0.020340448       -0.401630467        0.267079618   
7313        -0.83673208       -0.407080775       -0.620117165   

     gat1-deletion t=90 gat1-deletion t=120  
6783       -0.011495639        -0.123003954  
4511       -0.412510571         -0.46571332  
203        -0.100304906        -0.002882509  
6812        0.140825544         0.226003675  
4878        0.334607229          0.02180437  
...                 ...                 ...  
5770        0.364013496          0.18606493  
5224       -0.021479727        -0.060739158  
5425       -0.303342394        -0.227741076  
871         0.013043037         0.226003675  
7313       -0.647084213        -0.512985335  

[6499 rows x 8 columns]

In [27]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 加载数据
file_path = "../Data/household_power_consumption.txt"
data = pd.read_csv(file_path, sep=";", na_values=["?", "NA"])

# 1. 清理数据
# 转换日期和时间列为时间戳
data['Datetime'] = pd.to_datetime(data['Date'] + ' ' + data['Time'], format='%d/%m/%Y %H:%M:%S')

# 删除原始 Date 和 Time 列
data.drop(['Date', 'Time'], axis=1, inplace=True)

# 填补缺失值（可以选择填充或删除）
data.fillna(data.mean(), inplace=True)

# 2. 选择 X 和 Y
# 定义 X 和 Y 的列
feature_columns = [
    "Global_reactive_power",
    "Voltage",
    "Global_intensity",
    "Sub_metering_1",
    "Sub_metering_2",
    "Sub_metering_3"
]
target_column = "Global_active_power"

X = data[feature_columns]
Y = data[target_column]

# 3. 数据标准化
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 4. 数据分割为训练集和测试集
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state=42)

# 输出数据集的维度
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"Y_train shape: {Y_train.shape}")
print(f"Y_test shape: {Y_test.shape}")

/var/folders/s7/54k45_1544j5xllpj50wg60h0000gn/T/ipykernel_38215/2234431026.py:18: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  data.fillna(data.mean(), inplace=True)


X_train shape: (1660207, 6)
X_test shape: (415052, 6)
Y_train shape: (1660207,)
Y_test shape: (415052,)


In [28]:
data

Global_active_power  Global_reactive_power  Voltage  \
0                      4.216                  0.418   234.84   
1                      5.360                  0.436   233.63   
2                      5.374                  0.498   233.29   
3                      5.388                  0.502   233.74   
4                      3.666                  0.528   235.68   
...                      ...                    ...      ...   
2075254                0.946                  0.000   240.43   
2075255                0.944                  0.000   240.00   
2075256                0.938                  0.000   239.82   
2075257                0.934                  0.000   239.70   
2075258                0.932                  0.000   239.55   

         Global_intensity  Sub_metering_1  Sub_metering_2  Sub_metering_3  \
0                    18.4             0.0             1.0            17.0   
1                    23.0             0.0             1.0            16.0   
2                    23.0             0.0             2.0            17.0   
3                    23.0             0.0             1.0            17.0   
4                    15.8             0.0             1.0            17.0   
...                   ...             ...             ...             ...   
2075254               4.0             0.0             0.0             0.0   
2075255               4.0             0.0             0.0             0.0   
2075256               3.8             0.0             0.0             0.0   
2075257               3.8             0.0             0.0             0.0   
2075258               3.8             0.0             0.0             0.0   

                   Datetime  
0       2006-12-16 17:24:00  
1       2006-12-16 17:25:00  
2       2006-12-16 17:26:00  
3       2006-12-16 17:27:00  
4       2006-12-16 17:28:00  
...                     ...  
2075254 2010-11-26 20:58:00  
2075255 2010-11-26 20:59:00  
2075256 2010-11-26 21:00:00  
2075257 2010-11-26 21:01:00  
2075258 2010-11-26 21:02:00  

[2075259 rows x 8 columns]

In [30]:
X_train

array([[-1.10445372,  1.21135882, -0.86669733, -0.18348885, -0.22444507,
        -0.77031395],
       [-1.10445372, -0.07449833, -0.91198216, -0.18348885, -0.22444507,
        -0.77031395],
       [-0.22956448,  0.48457   , -0.82141249, -0.18348885, -0.22444507,
        -0.77031395],
       ...,
       [ 0.96671265, -0.3633503 ,  1.21640528,  1.28844743, -0.22444507,
        -0.77031395],
       [ 1.19882612, -1.50633444,  0.89941141, -0.18348885,  0.29409544,
        -0.77031395],
       [-0.62237189, -0.76091   ,  1.39754464, -0.18348885, -0.22444507,
        -0.77031395]])

In [47]:
def generate_multidimensional_mackey_glass(num_samples, tau=17, delta_t=0.1, num_attributes=4):
    data = np.zeros((num_samples, num_attributes))

    data[:tau] = np.random.rand(tau, num_attributes)

    # 定义系统的参数
    beta = 0.2
    gamma = 0.1
    n = 10

    # 按照因果关系生成后续样本
    for t in range(tau, num_samples):
        # 变量A的变化
        data[t, 0] = data[t - 1, 0] + (beta * data[t - tau, 0] / (1 + data[t - tau, 0] ** n) - gamma * data[t - 1, 0]) * delta_t

        # 变量B的变化，受A的滞后值以及B自身的影响
        data[t, 1] = data[t - 1, 1] + (0.25 * data[t - tau, 0] / (1 + data[t - tau, 0] ** n) - gamma * data[t - 1, 1]) * delta_t

        # 变量C的变化，受B的滞后值和随机噪声的影响
        data[t, 2] = data[t - 1, 2] + (0.15 * data[t - tau, 1] / (1 + data[t - tau, 1] ** n) - gamma * data[t - 1, 2]) * delta_t + np.random.normal(0, 0.05)

        # 变量D的变化，受C和D的延迟值的共同影响
        data[t, 3] = data[t - 1, 3] + (0.1 * data[t - tau, 2] / (1 + data[t - tau, 2] ** n) + 0.2 * data[t - 1, 3] - gamma * data[t - 1, 3]) * delta_t

    return data

In [32]:
generate_multidimensional_mackey_glass(100)

array([[0.17911232, 0.53397462, 0.76660899, 0.91631666],
       [0.2535497 , 0.88928875, 0.51953572, 0.76912559],
       [0.54032217, 0.85720013, 0.70358474, 0.77521258],
       [0.89440047, 0.13323206, 0.34923206, 0.77980265],
       [0.6806855 , 0.0109137 , 0.90046284, 0.44787443],
       [0.16051684, 0.16771556, 0.82125419, 0.95789369],
       [0.83780151, 0.83141506, 0.93478239, 0.94449441],
       [0.29782357, 0.76533911, 0.75731088, 0.59007987],
       [0.80704763, 0.41446363, 0.82529597, 0.77720349],
       [0.88513263, 0.03663919, 0.02898734, 0.58571761],
       [0.35731089, 0.37224017, 0.9937926 , 0.81148422],
       [0.43075377, 0.88077007, 0.67690751, 0.16425351],
       [0.80709543, 0.71552614, 0.4765325 , 0.16266754],
       [0.96751463, 0.69620164, 0.48221266, 0.72305296],
       [0.40692908, 0.61241031, 0.56158876, 0.28532912],
       [0.13381383, 0.38498384, 0.36622709, 0.9656612 ],
       [0.29979965, 0.66951079, 0.38913459, 0.84372005],
       [0.3003839 , 0.66729349,

In [34]:
import numpy as np

# 假设数据是 (n, 32)
n = 1  # 示例行数
data = np.arange(n * 32).reshape(n, 32)  # 模拟数据，形状为 (n, 32)

# 将每行的 32 列重塑为 (8, 4)，然后按行堆叠
reshaped_data = data.reshape(n, 8, 4).reshape(-1, 4)

print(data)
print("原始数据形状:", data.shape)
print("重塑后的数据形状:", reshaped_data.shape)
print(reshaped_data)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31]]
原始数据形状: (1, 32)
重塑后的数据形状: (8, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [37]:
expression_data_path = "../Data/dream3/DREAM3_GeneExpressionChallenge_ExpressionData_UPDATED.txt"
target_list_path = "../Data/dream3/DREAM3_GeneExpressionChallenge_TargetList.txt"

expression_df = pd.read_csv(expression_data_path, sep="\t")
target_list_df = pd.read_csv(target_list_path, sep="\t")

target_probe_ids = target_list_df["probeID"].dropna().tolist()

non_target_data = expression_df[~expression_df["ProbeID"].isin(target_probe_ids)]

non_target_data = non_target_data[0:30]




In [41]:
non_target_data.iloc[:,3:]

wt t=0   wt t=10   wt t=20   wt t=30   wt t=45   wt t=60   wt t=90  \
0        0  0.080088 -0.021480 -0.207893  0.070967 -0.066261 -0.063503   
1        0 -0.466758 -0.376290 -0.619178 -0.199123 -0.107018 -0.142740   
2        0 -0.312665 -0.146655 -0.640621 -0.097611 -0.200379 -0.304511   
3        0 -0.182692 -0.105678 -0.447844 -0.119024 -0.167358 -0.244887   
4        0  0.164884  0.182786  0.186065  0.103147  0.129734  0.107803   
5        0 -0.238787 -0.140124 -0.804880 -0.153157 -0.164786 -0.358396   
6        0  0.543720 -0.178874 -0.718964 -0.052416 -0.209141 -0.178874   
7        0  0.011588 -0.132248 -0.120352 -0.166073 -0.257011 -0.442545   
8        0  0.163268  0.205896  0.537424  0.186065  0.177882  0.080088   
9        0  0.438307  0.160040  0.272297  0.352916  0.312939 -0.191563   
10       0 -0.364012 -0.834307 -1.027154 -0.292782 -0.253384 -0.360645   
11       0  0.182786  0.103147  0.172994  0.120294  0.100051  0.067939   
12       0 -1.480782 -1.623399 -1.740712 -1.308011 -1.276199 -0.912267   
13       0  0.187707 -0.124328 -0.606916 -0.182692 -0.149259 -0.192825   
14       0 -0.723340 -0.523060 -0.387363 -0.361768 -0.668119 -0.737254   
15       0 -0.763836 -0.545968 -0.973060 -0.909197 -0.801573 -0.757877   
16       0 -0.164786 -0.112367 -0.609755 -0.021480 -0.089498 -0.137504   
17       0  0.032094 -0.027154  0.131313  0.174621 -0.067639 -0.066261   
18       0 -0.037031  0.222633  0.246395  0.172994 -0.064883 -0.046840   
19       0 -1.614003 -1.731618 -1.599318 -0.495695 -0.323082 -0.756169   
20       0 -0.339137 -0.550901 -0.646163 -0.302173 -0.470927 -0.695103   
21       0 -0.529071 -0.655352 -0.448901 -0.376290 -0.086784 -0.196607   
22       0  0.231075  0.161653  0.456009  0.384584  0.282790  0.181149   
23       0  0.137648  0.060397  0.689660  0.137648  0.084670  0.080088   
24       0  0.021804 -0.147958  0.039488 -0.020058 -0.280956 -0.415759   
25       0 -0.115033 -0.171207  0.020340 -0.173767 -0.210389 -0.321928   
26       0 -0.007196 -0.014355  0.459973  0.155213 -0.035624  0.021804   
27       0  0.015958 -0.128293  0.351074 -0.051024 -0.257011 -0.206643   
28       0 -0.481299 -0.347099  0.296899 -0.142740  0.081614  0.000000   
29       0 -0.277390  0.142417  0.067939  0.036526 -0.164786 -0.077243   

    wt t=120 gat1-deletion t=0 gat1-deletion t=10  ... gcn4-deletion t=90  \
0  -0.062122      -0.149259365       -0.166072676  ...           0.081614   
1  -0.210389       0.066427362        0.013043037  ...           0.302226   
2  -0.082703      -0.014355293        -0.22897257  ...          -0.478195   
3  -0.194087      -0.132247798       -0.247319935  ...          -0.302173   
4   0.186065       0.086201035        0.067938829  ...           0.112475   
5  -0.182692      -0.060739158        0.081613766  ...          -0.128293   
6  -0.115033      -0.075874867         0.10780329  ...          -0.303342   
7  -0.546956      -0.339137385       -0.380729449  ...          -0.473008   
8   0.067939      -0.015782997       -0.206643224  ...           0.058894   
9  -0.216610      -0.353887836       -0.566571641  ...          -0.018634   
10 -0.393965       0.078563669       -0.264236151  ...           0.067939   
11  0.186065       0.158429363       -0.049630768  ...          -0.012926   
12 -0.821302        0.49410907       -0.992768431  ...          -0.529071   
13 -0.020058       0.023269779        0.219269964  ...           0.038006   
14 -0.716332      -0.429749851       -0.901494455  ...          -0.325386   
15 -0.741575       0.351074441                  0  ...           0.114035   
16  0.064917       0.253257284       -0.167357928  ...          -0.048236   
17  0.272297       -0.22650853       -0.299830762  ...          -0.169925   
18  0.007232      -0.151858817       -0.308011315  ...          -0.296311   
19 -0.633199      -0.431890348       -1.622930351  ...          -0.201634   
20 -0.635058      -0.279768422       -0.426533138  ...          -0.408168   
21 -0.046840   

In [ ]:
non_target_data_array = non_target_data.values
reshaped_data = non_target_data_array.reshape(non_target_data_array.shape[0], 8, 4).transpose(0, 2, 1).reshape(-1, 4)
non_target_data = pd.DataFrame(reshaped_data, columns=["gat1", "col2", "col3", "col4"])

In [42]:
import numpy as np

# 假设有 100 个基因，每个基因 8 个时间点，4 个特征
n_genes = 100
n_timepoints = 8
n_features = 4
data = np.random.rand(n_genes * n_timepoints, n_features)

# 添加基因标签
gene_labels = np.repeat(np.arange(n_genes), n_timepoints)
stacked_data = np.hstack([data, gene_labels.reshape(-1, 1)])



In [46]:
stacked_data.shape

(800, 5)

In [49]:
data = generate_multidimensional_mackey_glass(20)

In [57]:
import numpy as np
from tigramite.independence_tests.cmiknn import CMIknn
from tigramite.pcmci import PCMCI
from tigramite.independence_tests.gpdc import GPDC
from tigramite import data_processing as pp
from config import *


def run_pcmci(data):
    data_np = data.values  # Convert to ndarray
    var_names = data.columns.tolist()
        # Optional: Keep variable names

    # Initialize Tigramite DataFrame
    pp_data = pp.DataFrame(data_np, var_names=var_names)
    # pp_data = pp.DataFrame(data_np)
    # GDPC: linear or simply non-linear data; CMIknn: complicated non-linear data but expensive
    gpdc = GPDC(significance=SIGNIFICANCE_METHOD)  # analytic or 'shuffle_test'/'bootstrap'
    pcmci = PCMCI(dataframe=pp_data, cond_ind_test=gpdc, verbosity=PC_VERBOSITY)
    results = pcmci.run_pcmci(tau_max=TAU_MAX, pc_alpha=PC_ALPHA, alpha_level=ALPHA_LEVEL)
    return results



In [58]:
result = run_pcmci(pd.DataFrame(data))


##
## Step 1: PC1 algorithm for selecting lagged conditions
##

Parameters:
independence test = gp_dc
tau_min = 1
tau_max = 3
pc_alpha = [0.05]
max_conds_dim = None
max_combinations = 1




/Users/sunyukang/opt/anaconda3/lib/python3.9/site-packages/scipy/optimize/_minpack_py.py:1010: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
/Users/sunyukang/opt/anaconda3/lib/python3.9/site-packages/scipy/optimize/_minpack_py.py:1010: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
/Users/sunyukang/opt/anaconda3/lib/python3.9/site-packages/scipy/optimize/_minpack_py.py:1010: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
/Users/sunyukang/opt/anaconda3/lib/python3.9/site-packages/scipy/optimize/_minpack_py.py:1010: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
/Users/sunyukang/opt/anaconda3/lib/python3.9/site-packages/s


## Resulting lagged parent (super)sets:

    Variable 0 has 0 link(s):

    Variable 1 has 0 link(s):

    Variable 2 has 0 link(s):

    Variable 3 has 0 link(s):

##
## Step 2: MCI algorithm
##

Parameters:

independence test = gp_dc
tau_min = 0
tau_max = 3
max_conds_py = None
max_conds_px = None

## Significant links at alpha = 0.1:

    Variable 0 has 6 link(s):
        (1 -2): pval = 0.00200 | val =  0.826
        (2  0): pval = 0.00800 | val =  0.782 | unoriented link
        (1 -1): pval = 0.00400 | val =  0.711
        (3 -1): pval = 0.01600 | val =  0.695
        (3  0): pval = 0.02400 | val =  0.657 | unoriented link
        (0 -1): pval = 0.07200 | val =  0.572

    Variable 1 has 2 link(s):
        (3  0): pval = 0.00600 | val =  0.722 | unoriented link
        (1 -1): pval = 0.05200 | val =  0.592

    Variable 2 has 5 link(s):
        (0  0): pval = 0.00800 | val =  0.782 | unoriented link
        (3 -1): pval = 0.05000 | val =  0.645
        (1 -2): pval = 0.03800 | val

In [62]:
result['val_matrix'].shape

(4, 4, 4)

In [64]:
pd.DataFrame(data, columns=['a','b','c','d']).columns.tolist()

['a', 'b', 'c', 'd']